### ISSUE TITLE
About how to compute the test accuracy on CLEVR.

### ISSUE THREAD

**Issue by Zhiquan-Wen** [shijx12/XNM-Net#3]
Hello. I see that answers in CLEVR are only for the train and validation set, and I cannot find the leaderboard about the CLEVR dataset. So how do you compute the test accuracy? Thanks.

**Comment by shijx12** [comment]
Hi, you need to send an e-mail to Johnson. Refer to this discussion: https://github.com/facebookresearch/clevr-dataset-gen/issues/2

**Comment by Zhiquan-Wen** [comment]
OK, thanks for your reply.
