### ISSUE TITLE
About how to test accuracy on vqa2.0. 

### ISSUE THREAD

**Issue by BAZINGAC** [shijx12/XNM-Net#4]
Hello,thanks for your work!In your code the test mode on the vqa2.0 dataset generates the predicted answer, but how to get the accuracy on the test set.

**Comment by shijx12** [comment]
Hi, you need to submit the answers to their online leaderboard. Refer to this website: https://eval.ai/web/challenges/challenge-page/514/overview

**Comment by BAZINGAC** [comment]
OK, thank you for your reply！
